// Generates 4 fresh throwaway test wallets (deployer, seller, scanner, agent)
// for the Ovelo escrow demo and writes their private keys to escrow/.env.
//
// Safety:
//  - Private keys are written ONLY to escrow/.env and are NEVER printed, logged
//    or echoed anywhere.
//  - Only the 4 public addresses are printed.
//  - Refuses to run if escrow/.env already exists, so existing keys are never
//    overwritten.
//
// Run with: npm run make-wallets
import { existsSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";

const envPath = join(dirname(fileURLToPath(import.meta.url)), "..", ".env");

if (existsSync(envPath)) {
  console.error(
    "escrow/.env already exists. Refusing to overwrite existing keys.\n" +
      "Delete escrow/.env first if you really want fresh wallets."
  );
  process.exit(1);
}

const specs = [
  { label: "deployer", variable: "DEPLOYER_PRIVATE_KEY" },
  { label: "seller", variable: "SELLER_PRIVATE_KEY" },
  { label: "scanner", variable: "SCANNER_PRIVATE_KEY" },
  { label: "agent", variable: "AGENT_PRIVATE_KEY" },
];

// Generate a brand new keypair per role. The full key is held only in memory
// until it is written to escrow/.env.
const wallets = specs.map((spec) => {
  const privateKey = generatePrivateKey();
  const account = privateKeyToAccount(privateKey);
  return { ...spec, privateKey, address: account.address };
});

const lines = [
  "# Ovelo escrow test wallets for Base Sepolia (TEST wallets only).",
  "# Generated by scripts/make-wallets.ts. Never use these with real funds.",
  "",
  ...wallets.map((w) => `${w.variable}=${w.privateKey}`),
  "",
];

writeFileSync(envPath, lines.join("\n"), { mode: 0o600 });

// The ONLY output: labeled public addresses. No private keys.
for (const w of wallets) {
  console.log(`${w.label} ${w.address}`);
}